// =============================================
// HELPER FUNCTIONS - Do not edit this file!
// =============================================
// These functions are provided for you to USE.
// You don't need to understand how they work yet.

/**
 * Returns a random integer between min and max (inclusive)
 * Example: randomBetween(1, 10) might return 7
 */
function randomBetween(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

/**
 * Returns true or false randomly (50/50 chance)
 * Example: coinFlip() might return true
 */
function coinFlip() {
  return Math.random() < 0.5;
}

/**
 * Returns valueIfTrue if condition is true, otherwise returns valueIfFalse
 * Example: choose(true, "yes", "no") returns "yes"
 * Example: choose(false, "yes", "no") returns "no"
 */
function choose(condition, valueIfTrue, valueIfFalse) {
  if (condition) {
    return valueIfTrue;
  } else {
    return valueIfFalse;
  }
}

/**
 * Updates the quest display with your variable values
 * Call this at the end of adventure.js to see your results!
 */
function updateQuest() {
  // Update quest title with student's quest item
  document.getElementById("quest-item").textContent =
    typeof questItem !== "undefined" ? questItem.toUpperCase() : "???";

  // Update hero emoji and name
  document.getElementById("hero-emoji").textContent =
    typeof heroEmoji !== "undefined" && heroEmoji ? heroEmoji : "";
  document.getElementById("hero-name").textContent =
    typeof heroName !== "undefined" ? heroName : "???";

  // Update status bar
  document.getElementById("health").textContent =
    typeof health !== "undefined" ? health : "???";
  document.getElementById("gold").textContent =
    typeof gold !== "undefined" ? gold : "???";

  // Update story text
  document.getElementById("story-text").textContent =
    typeof storyText !== "undefined" ? storyText : "Complete adventure.js to see your story!";

  // Update final status
  document.getElementById("final-health").textContent =
    typeof health !== "undefined" ? health : "???";
  document.getElementById("final-gold").textContent =
    typeof gold !== "undefined" ? gold : "???";

  // Update quest result
  document.getElementById("quest-result").textContent =
    typeof survivalMessage !== "undefined" ? survivalMessage : "Complete Part 6 to see your result!";
}
